name: Snake
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: vgobbi8
          outputs: |
            dist/snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
